### ISSUE TITLE
FAD does not work for all REAL data types

### ISSUE THREAD

**Issue by orlandini** [labmec/neopz#11]
The operators(*|+|-|/) are not being defined correctly for every data type (more precisely, for `REAL=float`).

The operators are defined through macros that rely on the `FadBinary(Mul|Div|Add|Minus)` classes (defined in `fadop.h`).

**Comment by philippedevloo** [comment]
Please show it through a small example. Make a unit test that demonstrates the bug

**Comment by orlandini** [comment]
Done. There is a new branch called FadTests with a new UnitTest design for catching these inconsistencies.

**Comment by thiagoquinelato** [comment]
Some code has been done (by @orlandini and me) in the FadTests branch and is being prepared to merge (in test phase now).

**Comment by philippedevloo** [comment]
Conseguirem resolver o problema de FAD/float? Foi muito “cabeludo”?

Abraços,

Philippe Devloo
phil@fec.unicamp.br
