### ISSUE TITLE
Document TPZMatrixRef

### ISSUE THREAD

**Issue by philippedevloo** [labmec/neopz#123]
When running Doxygen I observed the TPZMatrixRef is totally undocumented and I am not even sure if it is used anywhere.
Please explain what the intentions were

**Comment by orlandini** [comment]
I agree that its documentation should be more thorough, I didn't bother to do so as it is not a public header.

Its only usage is in `TPZMatrix<T>::Storage` method, which was used for speeding up, in a generic way, several matrix arithmetic operations when the matrices have the same sparsity pattern.

This was merged in #96 and it is explained in b0b75be .
