### ISSUE TITLE
UpdateBCValues

### ISSUE THREAD

**Issue by philippedevloo** [labmec/neopz#41]
This method turns the library not thread safe as it will overwrite member data of an object shared by many threads. I suggest to just delete the method. Whoever implements ConbributeBC should call the forcing function associated with the boundary condition

**Comment by gustavobat** [comment]
If the method isn't thread safe and does not enhance NeoPZ functionality I agree on removing it, but I believe we should leave this issue open until we ensure this change doesn't break anyone's code.

**Comment by orlandini** [comment]
should we close this issue by now?

**Comment by denisesiq** [comment]
I believe that this’ll be break the imposing Robing Boundary condition on reconstruction procedure. If I remember, we get the value of k_R on UpDateBCValues.

Denise

**Comment by gustavobat** [comment]
I couldn't find usages of UpdateBCValues in the current version of the error estimation code. Could you double-check if it is still in use, @denisesiq?
