### ISSUE TITLE
Perf-SubStruct target crashing with SIGKILL on Linux

### ISSUE THREAD

**Issue by orlandini** [labmec/neopz#53]
Configuring NeoPZ library as
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebugInfo
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-DBUILD_UNITTESTING=ON
-DUSING_LOG4CXX=ON
-DUSING_MKL=ON
-DUSING_METIS=ON
-DUSING_TBB=ON
-DBUILD_PERF_TESTS=ON
-DUSING_FAD=ON
```
in the `refactor-pthreads` branch (soon to be merged into `RefactorGeom`).

Reproduced in Ubuntu 20.04.2 LTS x86_64 and Manjaro 5.19.16-1. Apparently it is working in macOS. Dependencies versions are to be analysed.

**Comment by philippedevloo** [comment]
I believe it crashed because the current configuration requires at least 32 GB of Ram

Philippe Devloo
phil@fec.unicamp.br

**Comment by orlandini** [comment]
That's right.
Closing it now.
