### ISSUE TITLE
CMake files are in need of a refactor

### ISSUE THREAD

**Issue by orlandini** [labmec/neopz#54]
This issue is meant to keep track of the activities soon to be done in a branch (to be merged in the development branch `RefactorGeom`).

For now, the objectives are:
- [X] Agnostic dependency management through `FindXXX.cmake` modules
- [X] CMake cleanup
- [X] Writing source and header files explicitly <sup>1</sup>
- [X] Proper linkage with external libraries using `PRIVATE`, `PUBLIC`, `INTERFACE` cmake keywords
- [x] Filtering files to be installed (for instance, the subdirectory Publications should *definitely*  not be installed)
- [x] Review CMake options `USING_HDIVPIOLA` and `USING_NEW_SKYLMAT`
- [X] Solve issue with BLAS dependency on `pzgenericshape.h`
- [ ] What to do with Projects folder
- [X] Change how the library is installed
- [X] Make compile definitions private wherever possible using `target_compile_definitions` instead of `add_definitions`
- [X] Check log4cxx initialisation
- [X] Add interface for library options in `add_pz_target` (*e.g.*, this project requires that NeoPZ was compiled with MKL)
- [ ] Adjustments for WIN32 platforms

Please, if anyone sees any other changes that are needed, suggestions are more than welcome.

<sup>1</sup> See [here](https://cmake.org/cmake/help/latest/command/file.html#glob) and [here](https://stackoverflow.com/questions/1027247/is-it-better-to-specify-source-files-with-glob-or-each-file-individually-in-cmak/1060061#1060061) for reasons why.

**Comment by gustavobat** [comment]
Great, @orlandini ! I would include reviewing the need for options such as `USING_NEW_SKYLMAT` and `USING_HDIVPIOLA`.

**Comment by orlandini** [comment]
@gustavobat done.

**Comment by orlandini** [comment]
As pointed out by @thiagoquinelato, there are compiling issues on Debian based distros when not using MKL. There is information on that topic [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943712). I've added this to our checklist.

**Comment by orlandini** [comment]
I am not 100% happy with our current install.
In linux, we install a few files in:
/usr/local/CMake
and then
/usr/local/pzlib/include
/usr/local/pzlib/lib

It would be interesting to change that. I see no other libraries creating this /usr/local/CMake folder.

**Comment by orlandini** [comment]
I've added a point on how the usage of `target_compile_definitions` should be preferred instead of `add_definitions`.

**Comment by philippedevloo** [comment]
I agree. It should depend on the install directory. maybe /usr/local/pzlib/CMake ?

Philippe Devloo
phil@fec.unicamp.br

**Comment by orlandini** [comment]
As of bc6050e the SWIG python interfaces have been removed, since they will be replaced with pybind11 bindings.

**Comment by orlandini** [comment]
Added something that need to be taken care of regarding log initialisation

**Comment by gustavobat** [comment]
Any ideas on what to do with Projects directory? In my opinion, it could be put in a separate repository and eventually become an "Examples" showcase.

**Comment by philippedevloo** [comment]
The projects directory is the first line of defense against failed compilations. I would leave it be…

Philippe Devloo
***@***.***

**Comment by orlandini** [comment]
AFAIK we already have two repositories in GitHub that provide examples @gustavobat, H1Examples and HCurlExamples I think it would be nice if we could populate them
