### ISSUE TITLE
Shape/pzgenericshape.h dependency on BLAS

### ISSUE THREAD

**Issue by orlandini** [labmec/neopz#57]
Currently the file `Shape/pzgenericshape.h` has a dependency on some BLAS functions.
This file has no preprocessor directives to prevent its compilation when configuring NeoPZ without BLAS.
So

1. Is this dependency really necessary?
2. Is this file's `Shape` method still useful?

**Comment by philippedevloo** [comment]
The bias calls can easily be substituted by generic code.

And yes, the Shape method “should” substitute all shape methods of the different topologies. This would lead to
huge code reduction

Philippe Devloo
phil@fec.unicamp.br

**Comment by orlandini** [comment]
Ok. For now I've set preprocessor directives on that file to prevent compiling errors when not using BLAS. Should we close the issue or wait until pzgenericshape.h is  properly implemented and used?

**Comment by philippedevloo** [comment]
Let the issue open. This is important.

Philippe Devloo
phil@fec.unicamp.br

**Comment by philippedevloo** [comment]
Fran, why was the issue closed? Problem solved?

**Comment by orlandini** [comment]
I've changed the BLAS call to the corresponding `TPZMatrix::MultAdd` call, thus eliminating the explicit dependency.
