### ISSUE TITLE
Yet another TPZMaterial refactoring: reducing public interfaces

### ISSUE THREAD

**Issue by orlandini** [labmec/neopz#63]
During the refactoring process that resulted in PR #62, it was clear that the `TPZMaterial` class currently has quite a big interface.

There are many interfaces associated with materials with memory, materials with error analysis, among others, that pollute what is supposed to be a _common_ interface for all materials.

This issue aims to open a place for discussing approaches for dealing with this matter, before actual work is done on the matter.

**Proposal 1**
[Here](https://gist.github.com/orlandini/fcf43f7cc57f5be8d1e9d185a305ee72), I propose adding interfaces when needed through inheritance from classes virtually inherited from `TPZMaterial` (in order to assume that each child class will have only of copy of `TPZMaterial` class members). One caveat from this approach is that every class that inherits directly from `TPZMaterial`, *i.e.*, without any further added interfaces, should inherit from it virtually. I am not sure if there are means to ensure this at compile time.

**Proposal 2**
[Here](https://gist.github.com/orlandini/ba08209c1cf6b32c18dc7e6bfff45b70), I propose adding interfaces through inheritance from classes that _do not_ inherit from `TPZMaterial`. This would require that materials with added functionality initialise themselves manually through `SetMatWithXXX` methods in all their constructors. There is also the undesired `friend` relationship between `TPZMaterial` and the interface classes, in order to access the `fIsMatWithXXX` class member.

I would very much appreciate everyone's point of view on this subject.

**Comment by philippedevloo** [comment]
I prefer the second option. But would remove the interfaces of TPZMaterial that return a boolean. This could be implemented in the .cpp file doing a cast to the proper class.

**Comment by orlandini** [comment]
@philippedevloo for this to work, as can be seen [on this link](https://godbolt.org/z/9oPWdj), `TPZMaterial` would need at least one virtual method. This is not a problem. However, `TPZMaterial` would no longer be independent of the interfaces, as they would need to be included in the `.cpp` file (a forward declaration would not suffice). I like the idea of not having these dependencies. And keep in mind that the structs present in the current version of the proposals are not exposed at any moment, thus not cluttering the public interface.

Proposal 1: I like that the child class don't need to care about setting any flags, it must just implement its methods. We just need to be careful with the virtual inheritances.
Proposal 2: You eliminate the need for virtual inheritances, but then you transfer the tasks of setting the flags for the child classes.

**Comment by gustavobat** [comment]
I propose a third version, which is based on inheritance from a templatized version of `TPZMaterial`, denoted `TPZMaterialImpl` (we can choose a better name later) using variadic templates. Any number of interfaces can be put in the template parameters of `TPZMaterialImpl`. `TPZMaterialImpl` is agnostic of the interface classes and, in my opinion, the implementation of interfaces looks very clean. 

https://gist.github.com/gustavobat/eb5ba0d2b837ec82332f67a3c167bea2

To see it running:

https://godbolt.org/z/Gn7bPdG1z

**Comment by orlandini** [comment]
I really like your approach and, at first glance, I can see no caveats.

**Comment by philippedevloo** [comment]
For me this is the “winner”…

Philippe Devloo
***@***.***

**Comment by gustavobat** [comment]
Any ideas on the nomenclature of `TPZMaterialImpl`? Maybe something along the lines of `TPZMatInterfaceAdder`?

**Comment by philippedevloo** [comment]
TPZMaterialInterface

Philippe Devloo
***@***.***

**Comment by orlandini** [comment]
Closed with #90
