### ISSUE TITLE
TPZGeoEl::EldestAncestor() should return `this` when the element has no father

### ISSUE THREAD

**Issue by PedroLima92** [labmec/neopz#65]
I keep forgetting this method doesn't do that and, more often than I'd like to admit, getting bugs from it. I don't mean to pass on the blame for my bugs onto a poor defenseless function :smile:, but in this case I really think this should be the expected behaviour.

I mean, an unrefined element is the "eldest element" in its "refinement tree", isn't it?

I'll add this enhancement to the soon-to-come pull request of `MHM_HybridMixed` branch, if there are no objections.

I can see the potential for projects breaking due to this modification, though. We would need it tested before hand (which is why I'm proposing it to the scheduled pull request instead of directly merging it to `RefactorGeom`).

**Comment by gustavobat** [comment]
Your proposal makes sense to me. Unless this method is being used thoroughly in external projects, I don't think the change is harmful. In our repo, it only appears in the following lines:

https://github.com/labmec/neopz/blob/30686f7bbfeb402d40bc204012ea0077cae31d58/Projects/descontinuo/iRMS/TRMSimworxMeshGenerator.cpp#L1132

https://github.com/labmec/neopz/blob/30686f7bbfeb402d40bc204012ea0077cae31d58/Projects/descontinuo/iRMS/TRMSimworxMeshGenerator.cpp#L1196

If anyone objects to your proposal, you can always use the workaround used in `TRMSimworxMeshGenerator.cpp` and call the method if the element has no father:
```
if(gel->Father())
{
   ellip = dynamic_cast< TPZGeoElRefPattern<pzgeom::TPZEllipse3D> * > (gel->EldestAncestor());
}
else
{
     ellip = dynamic_cast< TPZGeoElRefPattern<pzgeom::TPZEllipse3D> * > (gel);
}
```

**Comment by orlandini** [comment]
I fully agree with you, @PedroLima92.

**Comment by philippedevloo** [comment]
I totally agree with your proposal Pedro. I don't think it will break codes...

**Comment by orlandini** [comment]
any updates?

**Comment by PedroLima92** [comment]
Yes @orlandini. I have it on my machine. Did you want to cherry pick it from `MHM_HybridMixed`? I'm still waiting on reviewers of that branch. I'm opening a pull request so I can make the notification to the reviewers from github.

**Comment by PedroLima92** [comment]
Since I'm here, I'd like to expand on the discussion a bit.

The current implementation of `TPZGeoEl::EldestAncestor` is set to `const`. This means that, when returning the `this` pointer, it would be set as a const pointer. That implies changing the return type of `TPZGeoEl::EldestAncestor` to a `const` pointer. Which doesn't seem like the intended implementation.

The way I got around it was by getting a non-const pointer to the element by going through its Mesh. So, in one line:
```cpp
if(!this->Father()){
    return fMesh->Element(this->fIndex); // this gets a non-const pointer to 'this'
}
```

Feels hacky, I know, but it does the job. Again, I could just remove the `const` qualification of the method, but the workaround conserves it fine from my perspective.

Opinions?

**Comment by philippedevloo** [comment]
You can also do a simple “cast” to a non-const pointer. It is as ugly, but it works and is more efficient

Philippe Devloo
***@***.***
